remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "aqua" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "ko-KR"
title: "고래뱃속"
subtitle: "Apple Developer Academy 3rd learner Geppetto's blog"
name: "Geppetto"
description: "World class Developer를 꿈꾸며 학습하고 기록하는 블로그입니다."
url: "https://saejinpark.github.io"
repository: "geppetto/geppetto.github.io"

# Site Author
author:
  name: "Geppetto"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "건축과도 같은 개발을 하고 싶습니다."
  location: "경기도 연천"
  links:
    - label: "590824@naver.com"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:590824@naver.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://saejinpark.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/saejinpark"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/saejinpark"

# Reading Files
include:
  - _pages

# Outputting
permalink: /:categories/:title/
paginate: 5 # 한 페이지에 보여줄 최근 게시물 수
paginate_path: /page:num/
timezone: Asia/Seoul

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Archives
category_archive:
  type: liquid
  path: /categories/
  
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

search: true
search_full_content: true  # 전체 콘텐츠 검색을 원하면 true로 설정
search_provider: lunr  # 기본 검색 제공자

head_scripts:
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js